# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MakeItPublic < Formula
  desc "make-it-public binary"
  homepage "https://gihub.com/ksysoev/make-it-public"
  version "0.4.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ksysoev/make-it-public/releases/download/v0.4.8/make-it-public_Darwin_x86_64.tar.gz"
      sha256 "56e370d6e5803c881a1fa7a8fd24a45694b2b288709e6e49ee844b131d469820"

      def install
        bin.install 'mit'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ksysoev/make-it-public/releases/download/v0.4.8/make-it-public_Darwin_arm64.tar.gz"
      sha256 "1274c420ce245872e61523284fe10a33dd02ae5a387b95cdcd2ebabf53868b3d"

      def install
        bin.install 'mit'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ksysoev/make-it-public/releases/download/v0.4.8/make-it-public_Linux_x86_64.tar.gz"
      sha256 "06abffd548a2026364d46403e5fc0d6f5003c039808afc48b712ea8a911f4f96"
      def install
        bin.install 'mit'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ksysoev/make-it-public/releases/download/v0.4.8/make-it-public_Linux_arm64.tar.gz"
      sha256 "8e553e46b18110ceda8ece066e7f8326384aa6772264cffb58f4bde6db177dc6"
      def install
        bin.install 'mit'
      end
    end
  end

  test do
    system "#{bin}/mit"
  end
end
